### ISSUE TITLE
"ReferenceError: assignment to undeclared variable Noise"

### ISSUE THREAD

**Issue by MilesVII** [RdStudios9145/perlin-simplex#1]
I'm not sure how this module is supposed to work, but importing it as ES6 module results in getting an aforementioned exception referring to [this line](https://github.com/RdStudios9145/perlin-simplex/blob/9ee14075d609264a4b0202a9bd9a1059940f477d/index.js#L14).

**Comment by RdStudios9145** [comment]
Hello

This is a repo that I cloned from an existing noise library to use it with typescript. You can look at the way I have used it [here](https://github.com/RdStudios9145/Minecraft/blob/master/src/chunk.ts)

Because of your issue, I have updated the repo with the correct usage. I have not tested them yet, but I believe that they work.

**Comment by IAALAI** [comment]
I also encountered this problem ， Uncaught ReferenceError: Noise is not defined
